variables:
  SEMVER: "0.0.1"
  UPDATE_REPO: "false"

include:
  - project: homelab/pipeline-catalog
    file: pipelines/release.yaml
  - project: homelab/pipeline-catalog
    file: pipelines/security.yaml
  - project: homelab/pipeline-catalog
    file: pipelines/stages.yaml

git-leaks:
  extends: .secrets_scan

semver:
  extends: .make-semver

chart:
  extends: .check-helm
  variables:
    CHECK_PATH: "chart/cluster-check"

create-changelog:
  extends: .changelog
  variables:
    version: "${SEMVER}"

tag-repo:
  extends: .create-tag
  variables:
    GIT_TAG: "${SEMVER}"