apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: robot-roles-binding
subjects:
  - kind: ServiceAccount   
    name: robot-account  
    namespace: robot   
roleRef:
  kind: Role
  name: robot-k8s-roles
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-read-binding
subjects:
  - kind: ServiceAccount   
    name: robot-account  
    namespace: robot   
roleRef:
  kind: Role
  name: flux-read
  apiGroup: rbac.authorization.k8s.io
