# k8s resources
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: robot-k8s-roles
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
---
# flux specific resources
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-read
rules:
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["gitrepositories", "helmrepositories", "buckets", "ocirepositories"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["get", "list", "watch"]
