# Default values for cluste-check.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  repository: registry.dev.local/homelab/cluster-checker
  tag: "latest"
  pullPolicy:  Always

schedule: "0 9 * * *"  # everyday at 9 am
command: ["/bin/bash", "-c"]
args: [" /app/scripts/entrypoint.sh"]

# can put secrets. Ex. slack token to send notifications
# need to create secret manually 
# name of secret and the value of the secret
secretsEnv: 
  enabled: true 
  secrets:  
    robot-secrets: SLACK_URL

# Set timer for a job, in case it keeps running for some reason
activeDeadlineSeconds: 60

env: 
  NOTIFY: "true"              # allow notifications or not, used for testing in case just want to test tests
  OUTPUT_DIR: "/shared"       # TODO: where things will be saved


# TODO save reports on host 
savePath: "/myHostDir"    
