apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-check 
  annotations:
    sidecar.istio.io/inject: "false"  # disable istio so delete pod when job is done
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: robot-account 
          containers:
          - name: runner 
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: {{ .Values.command | toJson }} 
            args: {{ .Values.args | toJson }}
            env:
            {{- range $key, $value := .Values.env }}
              - name: {{ $key }}
                values: {{ $value }}
            {{- end }}
            {{ if .Values.secretsEnv.enabled }}
            {{- range $name, $value := .Values.secretsEnv.secrets }}
              - name: {{ $value }} 
                valueFrom:
                  secretKeyRef:
                    name: {{ $name }}
                    key: {{ $value }} 
            {{- end }}
            {{- end }}
          restartPolicy: OnFailure
